feat: update readme
eve-autonomy/ad_status_lamp_manager pull request #1
Opened 2022-06-07 15:38 UTC by yn-mrse

2022-06-22 11:07 UTC, MasaakiWatanabeTier4 requested changes

2022-06-22 11:07 UTC, MasaakiWatanabeTier4 commented on README.md
> +# autonomous_driving_status_lamp_manager
```suggestion
# Status lamp manager for autonomous driving
```

2022-06-22 11:07 UTC, MasaakiWatanabeTier4 commented on README.md
> +By switching the lighting pattern of the lamp, this node informs the transport manager of the system status.
要検討

2022-06-22 11:07 UTC, MasaakiWatanabeTier4 commented on README.md
> +The lighting pattern is defined as follows.
```suggestion
Lighting patterns are defined as follows;
```

2022-06-22 11:07 UTC, MasaakiWatanabeTier4 commented on README.md
> +      <td>During system startup</td>
```suggestion
      <td>System starting up</td>
```

2022-06-22 11:07 UTC, MasaakiWatanabeTier4 commented on README.md
> +      <td>Blinks every second</td>
```suggestion
      <td>Blink once every second</td>
```

2022-06-22 11:07 UTC, MasaakiWatanabeTier4 commented on README.md
> +      <td>Flashes twice quickly on a regular basis</td>
```suggestion
      <td>Flash twice a second</td>
```

2022-06-22 11:07 UTC, MasaakiWatanabeTier4 commented on README.md
> +      <td>Keeps lighting</td>
```suggestion
      <td>Light up</td>
```

2022-06-22 11:07 UTC, MasaakiWatanabeTier4 commented on README.md
> +      <td>During system shutdown</td>
```suggestion
      <td>System shutting down</td>
```

2022-06-22 11:07 UTC, MasaakiWatanabeTier4 commented on README.md
> +      <td>Blinks every second</td>
```suggestion
      <td>Blink once every second</td>
```

2022-06-22 11:07 UTC, MasaakiWatanabeTier4 commented on README.md
> +      <td>Completes system shutdown</td>
```suggestion
      <td>Power off</td>
```

2022-06-22 11:07 UTC, MasaakiWatanabeTier4 commented on README.md
> +      <td>Keeps going off</td>
```suggestion
      <td>Off</td>
```

2022-06-22 11:07 UTC, MasaakiWatanabeTier4 commented on README.md
> +  - from [autoware_state_machine](https://github.com/eve-autonomy/autoware_state_machine)
```suggestion
  - from [autoware_state_machine](https://github.com/eve-autonomy/autoware_state_machine/)
```

2022-06-22 11:07 UTC, MasaakiWatanabeTier4 commented on README.md
> +  - to [dio_ros_driver](https://github.com/tier4/dio_ros_driver)
```suggestion
  - to [dio_ros_driver](https://github.com/tier4/dio_ros_driver/)
```

2022-06-22 11:07 UTC, MasaakiWatanabeTier4 commented on README.md
> +    - `/dio/dout0` : GPIO output topic. (this topic is remapping from /ad_status_lamp_out)
```suggestion
    - `/dio/dout0` : GPIO output topic. (this topic is remapped from `/ad_status_lamp_out`)
```

2022-06-23 08:52 UTC, merged

2022-06-23 09:10 UTC, seungseok-oh commented on README.md
> +By switching the lighting pattern of the lamp, this node informs the transport manager of the system status.
This node changes the lighting pattern of the lamp for the operation manager to check the system status.